name: cash_lander2
description: A new Flutter project.
publish_to: "none" # This prevents accidental publishing to pub.dev
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  go_router: ^15.1.3
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  flutter_otp_text_field: ^1.1.0+2
  flutter_timer_countdown: ^1.0.7
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_functions: ^5.6.1
  http: ^1.4.0
  phosphor_flutter: ^2.1.0
  percent_indicator: ^4.2.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0124D3"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png

  # Add these parameters to control image quality and sizing
  fill: false # Don't stretch image to fill screen
  fullscreen: false # Keep status bar visible

  # Control image positioning and sizing
  android_gravity: center # center, top, bottom, left, right
  ios_content_mode: scaleAspectFit # scaleAspectFit, scaleAspectFill, center

  # Web specific settings for better quality
  web_image_mode: center # center, contain, cover, fill, fitHeight, fitWidth

  # Platform-specific configurations for better quality
  android:
    image: assets/images/logo.png
    gravity: center

  ios:
    image: assets/images/logo.png
    content_mode: scaleAspectFit

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#0124D3"
    image_positioning: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png

  fonts:
    - family: Campton
      fonts:
        - asset: assets/fonts/CamptonBook.otf
          weight: 400
        - asset: assets/fonts/CamptonExtraBold.otf
          weight: 800
        - asset: assets/fonts/CamptonMedium.otf
          weight: 500
        - asset: assets/fonts/CamptonBold.otf
          weight: 700
        - asset: assets/fonts/CamptonSemiBold.otf
          weight: 600
