name: cash_lander2
description: A new Flutter project.
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  go_router: ^15.1.3
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0124D3"
  image: assets/images/logo2.png
  image_dark: assets/images/logo2.png

  android_12:
    image: assets/images/logo2.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo2.png
    icon_background_color_dark: "#0124D3"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png

  fonts:
    - family: Campton
      fonts:
        - asset: assets/fonts/CamptonBook.otf
          weight: 400
        - asset: assets/fonts/CamptonExtraBold.otf
          weight: 800
        - asset: assets/fonts/CamptonMedium.otf
          weight: 500
        - asset: assets/fonts/CamptonBold.otf
          weight: 700
        - asset: assets/fonts/CamptonSemiBold.otf
          weight: 600
